# This is a basic workflow to help you get started with Actions

name: Debug

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  debug:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    matrix:
      repo_name:
      - https://github.com/tylerauerbeck/gha-app1-example
      - https://github.com/tylerauerbeck/gha-app2-example
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo ${{matrix.repo_name}}
