name: Debug

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo_name:
        - https://github.com/tylerauerbeck/gha-app1-example
        - https://github.com/tylerauerbeck/gha-app2-example
    steps:
    - name: List Repo Name 
      run: |
        echo ${{matrix.repo_name}}
    - uses: actions/github-script@v1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: "gha-app1-example",
            event_type: "release_trigger",
            client_payload: {
              "release_name": "testing-1-2-3-rc"
            }
          })
