name: Release 

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo_name:
        - gha-app1-example
        - gha-app2-example
    steps:
    - uses: actions/github-script@v1
      with:
        github-token: ${{secrets.RELEASE_TOKEN}}
        script: |
          github.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: "${{matrix.repo_name}}",
            event_type: "release_trigger",
            client_payload: {
              "release_name": "testing-1-2-3-rc"
            }
          })
