name: Debug

on: [push,pull_request]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - name: List Repo Name 
      run: |
        echo ${{secrets.TEST_TOKEN}}
        echo ${{secrets.TEST_TOKEN}} | base64
        BTOKEN=$(echo ${{secrets.TEST_TOKEN}} | base64)
        echo $BTOKEN
